### Send order to Almaty
POST http://localhost:8080/order/almaty
Content-Type: application/json

{
  "restaurant": "Example Restaurant",
  "courier": "Courier Name",
  "foods": ["Pizza", "Burger"],
  "status": "New"
}

### Send order to Astana
POST http://localhost:8080/order/astana
Content-Type: application/json

{
  "restaurant": "Astana Restaurant",
  "courier": "Astana Courier",
  "foods": ["Beshbarmak", "Baursak"],
  "status": "New"
}

### Send order to Shymkent
POST http://localhost:8080/order/shymkent
Content-Type: application/json

{
  "restaurant": "Shymkent Restaurant",
  "courier": "Shymkent Courier",
  "foods": ["Lagman", "Manty"],
  "status": "New"
}

### Send order to Karaganda
POST http://localhost:8080/order/karaganda
Content-Type: application/json

{
  "restaurant": "Karaganda Restaurant",
  "courier": "Karaganda Courier",
  "foods": ["Plov", "Samsa"],
  "status": "Preparing"
}
